### ISSUE TITLE
Publish to maven central

### ISSUE THREAD

**Issue by jaxxar** [advantagefse/json-logic-kotlin#6]
json-logic-kotlin is published only to jcenter. Please consider publishing it also to mavenCentral, as jcenter [is shutting down in May](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

**Comment by csknns** [comment]
Fixed by advantagefse/json-logic-kotlin#8 and included in version [0.9.7.1](https://github.com/advantagefse/json-logic-kotlin/releases/tag/0.9.7.1)
